name: Enforce PR base branch

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR base branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" = "main" ]; then
            echo "❌ PRs must target staging, not master."
            exit 1
          fi